//! A02 host/guest bridge for disposable Windows Sandbox attempts.
//!
//! The module deliberately does not expose a host command. Callers declare the
//! files to import, the fixed probe entrypoint is generated by this module, and
//! exported files are accepted only through a bounded receipt protocol.
use anyhow::{Context, Result, ensure};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    collections::BTreeMap,
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Stdio,
    time::Duration,
};
use tokio::{process::Command, time};
use tokio_util::sync::CancellationToken;

use crate::runtime::windows_runtime::{
    WindowsRuntimeAdapter, WindowsRuntimeConfig, WindowsRuntimeEntry, WindowsRuntimeMode,
};

pub const SANDBOX_SCHEMA_VERSION: u32 = 1;
pub const GUEST_TOOLS: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisTools";
pub const GUEST_INPUT: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisInput";
pub const GUEST_OUTPUT: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisOutput";
pub const GUEST_PYTHON: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisPython";
pub const GUEST_ZIG: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisZig";
pub const GUEST_TINYINST: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisTinyInst";
pub const GUEST_LLVM: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisLLVM";
const RECEIPT_FILE: &str = "session.json";

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum SandboxEntrypoint {
    #[serde(rename = "BOUNDARY_PROBE")]
    BoundaryProbe,
    #[serde(rename = "ORIGINAL_PE")]
    OriginalPe,
    #[serde(rename = "WINDOWS_PYTHON")]
    WindowsPython,
    #[serde(rename = "WINDOWS_NATIVE_SOURCE")]
    WindowsNativeSource,
    #[serde(rename = "TINY_INST_PE")]
    TinyInstPe,
    #[serde(rename = "LLVM_LIBFUZZER_PREBUILT")]
    LibFuzzerPrebuilt,
}

impl SandboxEntrypoint {
    fn guest_script(self) -> &'static str {
        match self {
            Self::BoundaryProbe => "probe.ps1",
            Self::OriginalPe => "run-pe.ps1",
            Self::WindowsPython => "run-python.ps1",
            Self::WindowsNativeSource => "run-native-source.ps1",
            Self::TinyInstPe => "run-tinyinst.ps1",
            Self::LibFuzzerPrebuilt => "run-libfuzzer.ps1",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxMapping {
    pub host: PathBuf,
    pub guest: String,
    pub read_only: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxSession {
    pub run_id: String,
    pub attempt_id: String,
    pub session_id: String,
    pub target_sha256: String,
    pub config_sha256: String,
    pub memory_mb: u32,
}

impl SandboxSession {
    pub fn validate(&self) -> Result<()> {
        for (name, value) in [
            ("run_id", &self.run_id),
            ("attempt_id", &self.attempt_id),
            ("session_id", &self.session_id),
        ] {
            ensure!(
                is_identifier(value),
                "{name} must contain 1-128 ASCII letters, digits, hyphens, or underscores"
            );
        }
        ensure!(
            self.session_id
                .starts_with(&format!("{}-", self.attempt_id)),
            "session_id must be namespaced by attempt_id"
        );
        ensure!(
            is_sha256(&self.target_sha256) && is_sha256(&self.config_sha256),
            "target and configuration hashes must be SHA-256 values"
        );
        ensure!(
            (2048..=8192).contains(&self.memory_mb),
            "memory_mb must be between 2048 and 8192"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxFileTransfer {
    pub source: PathBuf,
    pub path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxArtifact {
    pub path: String,
    pub sha256: String,
    pub size: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxReceipt {
    pub schema_version: u32,
    pub run_id: String,
    pub attempt_id: String,
    pub session_id: String,
    pub status: String,
}

impl SandboxReceipt {
    fn validate(&self, session: &SandboxSession) -> Result<()> {
        ensure!(
            self.schema_version == SANDBOX_SCHEMA_VERSION,
            "unsupported sandbox receipt schema"
        );
        ensure!(
            self.run_id == session.run_id
                && self.attempt_id == session.attempt_id
                && self.session_id == session.session_id,
            "sandbox receipt belongs to another attempt"
        );
        ensure!(
            ["COMPLETED", "ERROR"].contains(&self.status.as_str()),
            "sandbox receipt status must be COMPLETED or ERROR"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxOutputPolicy {
    pub required_files: BTreeSet<String>,
    pub optional_files: BTreeSet<String>,
    pub max_file_bytes: u64,
    pub max_total_bytes: u64,
}

impl SandboxOutputPolicy {
    pub fn probe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "output-marker.txt".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn original_pe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn windows_python() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn windows_native_source() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "compile.stderr.log".into(),
                "compile.stdout.log".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 4 * 1024 * 1024,
        }
    }

    pub fn tiny_inst_pe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "coverage.txt".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn lib_fuzzer_prebuilt() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "compile.stderr.log".into(),
                "compile.stdout.log".into(),
                "corpus.zip".into(),
                "crash-input.bin".into(),
                "fuzz-executed.txt".into(),
                "fuzzer.stderr.log".into(),
                "fuzzer.stdout.log".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "replay.stderr.log".into(),
                "replay.stdout.log".into(),
            ]),
            max_file_bytes: 2 * 1024 * 1024,
            max_total_bytes: 8 * 1024 * 1024,
        }
    }

    fn allowed(&self, path: &str) -> bool {
        self.required_files.contains(path) || self.optional_files.contains(path)
    }

    fn validate(&self) -> Result<()> {
        ensure!(
            self.required_files.contains(RECEIPT_FILE),
            "the fixed export protocol requires session.json"
        );
        ensure!(
            self.required_files.is_disjoint(&self.optional_files),
            "required and optional output files overlap"
        );
        ensure!(
            self.max_file_bytes > 0
                && self.max_total_bytes >= self.max_file_bytes
                && self.max_total_bytes <= 64 * 1024 * 1024,
            "invalid sandbox output size policy"
        );
        for file in self.required_files.iter().chain(self.optional_files.iter()) {
            ensure!(
                relative_path(file).is_some(),
                "invalid output file path: {file}"
            );
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxOutput {
    pub receipt: SandboxReceipt,
    pub artifacts: Vec<SandboxArtifact>,
    pub total_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxExecution {
    pub launcher_exit_code: Option<i32>,
    pub remote_session_started: bool,
    pub remote_session_closed: bool,
    pub timed_out: bool,
    pub cancelled: bool,
    pub cleanup_output: String,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreparedSandbox {
    pub entrypoint: SandboxEntrypoint,
    pub session: SandboxSession,
    pub root: PathBuf,
    pub input: PathBuf,
    pub output: PathBuf,
    pub tools: PathBuf,
    pub config: PathBuf,
    pub manifest: PathBuf,
    pub input_files: Vec<SandboxArtifact>,
    pub tool_files: Vec<SandboxArtifact>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SandboxSpec {
    pub entrypoint: SandboxEntrypoint,
    pub session: SandboxSession,
    pub root: PathBuf,
    pub inputs: Vec<SandboxFileTransfer>,
    pub tools: Vec<SandboxFileTransfer>,
    #[serde(default)]
    pub mappings: Vec<SandboxMapping>,
    pub runtime_config: Option<WindowsRuntimeConfig>,
}

pub fn prepare(spec: &SandboxSpec) -> Result<PreparedSandbox> {
    spec.session.validate()?;
    let runtime_config = match (&spec.entrypoint, &spec.runtime_config) {
        (SandboxEntrypoint::BoundaryProbe, None) => None,
        (SandboxEntrypoint::OriginalPe, Some(config)) => {
            config.validate()?;
            ensure!(
                matches!(
                    config.adapter,
                    WindowsRuntimeAdapter::OriginalPe32 | WindowsRuntimeAdapter::OriginalPe64
                ),
                "the original PE entrypoint requires a PE adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the original PE entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the original PE entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            Some(config)
        }
        (SandboxEntrypoint::BoundaryProbe, Some(_)) => {
            return Err(anyhow::anyhow!(
                "the boundary probe does not accept a runtime configuration"
            ));
        }
        (SandboxEntrypoint::OriginalPe, None) => {
            return Err(anyhow::anyhow!(
                "the original PE entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::WindowsPython, Some(config)) => {
            config.validate()?;
            ensure!(
                config.adapter == WindowsRuntimeAdapter::PythonCall,
                "the Windows Python entrypoint requires the Python adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::Function { .. }),
                "the Windows Python entrypoint requires a function entry"
            );
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_PYTHON
                        && mapping.read_only
                        && mapping.host.join("python.exe").is_file()
                }),
                "the Windows Python entrypoint requires a read-only Python runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::WindowsPython, None) => {
            return Err(anyhow::anyhow!(
                "the Windows Python entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::WindowsNativeSource, Some(config)) => {
            config.validate()?;
            ensure!(
                config.adapter == WindowsRuntimeAdapter::NativeSource,
                "the native-source entrypoint requires the native-source adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the native-source entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the native-source entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_ZIG
                        && mapping.read_only
                        && mapping.host.join("zig.exe").is_file()
                }),
                "the native-source entrypoint requires a read-only Zig runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::WindowsNativeSource, None) => {
            return Err(anyhow::anyhow!(
                "the native-source entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::TinyInstPe, Some(config)) => {
            config.validate()?;
            ensure!(
                matches!(
                    config.adapter,
                    WindowsRuntimeAdapter::OriginalPe32 | WindowsRuntimeAdapter::OriginalPe64
                ),
                "the TinyInst entrypoint requires a PE adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the TinyInst entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the TinyInst entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_TINYINST
                        && mapping.read_only
                        && mapping.host.join("litecov.exe").is_file()
                }),
                "the TinyInst entrypoint requires a read-only TinyInst runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::TinyInstPe, None) => {
            return Err(anyhow::anyhow!(
                "the TinyInst entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::LibFuzzerPrebuilt, Some(config)) => {
            config.validate()?;
            ensure!(
                config.mode == WindowsRuntimeMode::Fuzz,
                "the libFuzzer entrypoint requires FUZZ mode"
            );
            ensure!(
                config.adapter == WindowsRuntimeAdapter::LibFuzzerPrebuilt,
                "the libFuzzer entrypoint requires the prebuilt libFuzzer adapter"
            );
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_LLVM
                        && mapping.read_only
                        && mapping.host.join("bin/clang.exe").is_file()
                }),
                "the libFuzzer entrypoint requires a read-only LLVM runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::LibFuzzerPrebuilt, None) => {
            return Err(anyhow::anyhow!(
                "the libFuzzer entrypoint requires a runtime configuration"
            ));
        }
    };
    for mapping in &spec.mappings {
        ensure!(
            mapping.host.is_absolute() && mapping.host.is_dir() && !is_reparse_point(&mapping.host),
            "sandbox mapping host must be an absolute directory"
        );
        ensure!(
            (mapping.guest == GUEST_PYTHON
                || mapping.guest == GUEST_ZIG
                || mapping.guest == GUEST_TINYINST
                || mapping.guest == GUEST_LLVM)
                && mapping.read_only,
            "only fixed read-only Python, Zig, TinyInst, and LLVM mappings are currently supported"
        );
        ensure!(
            mapping.host != spec.root.join("input")
                && mapping.host != spec.root.join("output")
                && mapping.host != spec.root.join("tools"),
            "runtime mapping may not overlap attempt directories"
        );
    }
    ensure!(
        spec.inputs.len() <= 256 && spec.tools.len() <= 128,
        "a sandbox attempt may import at most 256 inputs and 128 tools"
    );
    if spec.root.exists() {
        ensure!(spec.root.is_dir(), "sandbox root is not a directory");
        ensure!(
            fs::read_dir(&spec.root)?.next().is_none(),
            "sandbox root must be empty so outputs cannot belong to an older attempt"
        );
    } else {
        fs::create_dir_all(&spec.root)?;
    }
    ensure!(
        !is_reparse_point(&spec.root),
        "sandbox root may not be a reparse point"
    );
    let input = spec.root.join("input");
    let output = spec.root.join("output");
    let tools = spec.root.join("tools");
    for directory in [&input, &output, &tools] {
        fs::create_dir(directory)?;
        ensure!(
            !is_reparse_point(directory),
            "sandbox directory may not be a reparse point"
        );
    }

    let input_files = import_files(&spec.inputs, &input)?;
    let tool_files = import_files(&spec.tools, &tools)?;
    ensure!(
        tool_files
            .iter()
            .any(|item| item.path == spec.entrypoint.guest_script()),
        "the sandbox tool set is missing its fixed entrypoint"
    );
    write_json(
        &input.join(RECEIPT_FILE),
        &json!({
            "schema_version": SANDBOX_SCHEMA_VERSION,
            "run_id": spec.session.run_id,
            "attempt_id": spec.session.attempt_id,
            "session_id": spec.session.session_id,
            "target_sha256": spec.session.target_sha256,
            "config_sha256": spec.session.config_sha256
        }),
    )?;
    let receipt_artifact = artifact(&input.join(RECEIPT_FILE), RECEIPT_FILE)?;
    let input_files = merge_artifacts(input_files, receipt_artifact);
    let input_files = if let Some(runtime_config) = runtime_config {
        let runtime_path = input.join("runtime-config.json");
        write_json(&runtime_path, &serde_json::to_value(runtime_config)?)?;
        let runtime_artifact = artifact(&runtime_path, "runtime-config.json")?;
        merge_artifacts(input_files, runtime_artifact)
    } else {
        input_files
    };
    ensure!(
        input_files
            .iter()
            .any(|item| item.sha256 == spec.session.target_sha256),
        "the imported input set must contain the declared target hash"
    );
    if let Some(runtime_config) = runtime_config {
        ensure!(
            input_files
                .iter()
                .any(|item| item.path == runtime_config.target_path
                    && item.sha256 == runtime_config.target_sha256),
            "the imported input set must contain the declared runtime target"
        );
    }

    let manifest = spec.root.join("host-manifest.json");
    write_json(
        &manifest,
        &json!({
            "schema_version": SANDBOX_SCHEMA_VERSION,
            "session": spec.session,
            "guest_paths": {
                "tools": GUEST_TOOLS,
                "input": GUEST_INPUT,
                "output": GUEST_OUTPUT
            },
            "policy": {
                "networking": "DISABLED",
                "v_gpu": "DISABLED",
                "clipboard_redirection": "DISABLED",
                "printer_redirection": "DISABLED",
                "audio_input_redirection": "DISABLED",
                "video_input_redirection": "DISABLED",
                "protected_client": "ENABLED",
                "memory_mb": spec.session.memory_mb,
                "input_read_only": true,
                "output_read_only": false
            },
            "input_files": input_files,
            "tool_files": tool_files,
            "entrypoint": spec.entrypoint,
            "mappings": spec.mappings
        }),
    )?;
    let config = spec.root.join("sandbox.wsb");
    fs::write(
        &config,
        sandbox_config(
            &tools,
            &input,
            &output,
            spec.session.memory_mb,
            spec.entrypoint,
            &spec.mappings,
        )?,
    )?;
    Ok(PreparedSandbox {
        entrypoint: spec.entrypoint,
        session: spec.session.clone(),
        root: spec.root.clone(),
        input,
        output,
        tools,
        config,
        manifest,
        input_files,
        tool_files,
    })
}

pub fn verify_inputs(prepared: &PreparedSandbox) -> Result<()> {
    for (base, expected) in prepared
        .input_files
        .iter()
        .map(|expected| (&prepared.input, expected))
        .chain(
            prepared
                .tool_files
                .iter()
                .map(|expected| (&prepared.tools, expected)),
        )
    {
        let path = base.join(&expected.path);
        ensure!(
            path.is_file(),
            "sandbox input is missing: {}",
            expected.path
        );
        ensure!(!is_reparse_point(&path), "sandbox input is a reparse point");
        let actual = artifact(&path, &expected.path)?;
        ensure!(
            actual == *expected,
            "sandbox input changed after preparation: {}",
            expected.path
        );
    }
    Ok(())
}

pub fn collect_output(
    prepared: &PreparedSandbox,
    policy: &SandboxOutputPolicy,
) -> Result<SandboxOutput> {
    policy.validate()?;
    ensure!(
        prepared.output.is_dir() && !is_reparse_point(&prepared.output),
        "sandbox output directory is missing or unsafe"
    );
    let mut artifacts = Vec::new();
    let mut total_bytes = 0u64;
    for entry in fs::read_dir(&prepared.output)? {
        let entry = entry?;
        let path = entry.path();
        ensure!(path.is_file(), "sandbox output must contain files only");
        ensure!(
            !is_reparse_point(&path),
            "sandbox output is a reparse point"
        );
        let relative = path
            .strip_prefix(&prepared.output)
            .map_err(|_| anyhow::anyhow!("output path escapes its directory"))?
            .to_string_lossy()
            .replace('\\', "/");
        ensure!(
            policy.allowed(&relative),
            "sandbox output is not allowed by the export policy: {relative}"
        );
        let artifact = artifact(&path, &relative)?;
        ensure!(
            artifact.size <= policy.max_file_bytes,
            "sandbox output exceeds the per-file limit: {relative}"
        );
        total_bytes = total_bytes
            .checked_add(artifact.size)
            .ok_or_else(|| anyhow::anyhow!("sandbox output size overflow"))?;
        artifacts.push(artifact);
    }
    ensure!(
        total_bytes <= policy.max_total_bytes,
        "sandbox output exceeds the total size limit"
    );
    let actual: BTreeSet<_> = artifacts.iter().map(|item| item.path.as_str()).collect();
    for required in &policy.required_files {
        ensure!(
            actual.contains(required.as_str()),
            "required sandbox output is missing: {required}"
        );
    }
    let receipt_path = prepared.output.join(RECEIPT_FILE);
    let receipt_text = fs::read_to_string(&receipt_path)
        .with_context(|| format!("cannot read sandbox receipt {receipt_path:?}"))?;
    let receipt: SandboxReceipt = serde_json::from_str(receipt_text.trim_start_matches('\u{feff}'))
        .with_context(|| format!("invalid sandbox receipt {receipt_path:?}"))?;
    receipt.validate(&prepared.session)?;
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(SandboxOutput {
        receipt,
        artifacts,
        total_bytes,
    })
}

pub async fn run_probe(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::BoundaryProbe,
        "run_probe is only for the harmless boundary probe"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_original_pe(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::OriginalPe,
        "run_original_pe is only for declared original PE attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_windows_python(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::WindowsPython,
        "run_windows_python is only for declared Windows Python attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_native_source(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::WindowsNativeSource,
        "run_native_source is only for declared native-source attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_tinyinst(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::TinyInstPe,
        "run_tinyinst is only for declared TinyInst PE attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_libfuzzer(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::LibFuzzerPrebuilt,
        "run_libfuzzer is only for declared prebuilt libFuzzer attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

async fn run_sandbox(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    let system_root = std::env::var_os("SystemRoot")
        .map(PathBuf::from)
        .unwrap_or_else(|| r"C:\Windows".into());
    let sandbox = system_root.join(r"System32\WindowsSandbox.exe");
    ensure!(sandbox.is_file(), "Windows Sandbox executable is missing");

    let stdout = fs::File::create(prepared.root.join("sandbox.stdout.log"))?;
    let stderr = fs::File::create(prepared.root.join("sandbox.stderr.log"))?;
    let mut launcher = Command::new(&sandbox)
        .arg(&prepared.config)
        .stdout(Stdio::from(stdout))
        .stderr(Stdio::from(stderr))
        .kill_on_drop(true)
        .spawn()?;
    let mut launcher_exit_code = None;
    if let Ok(status) = time::timeout(Duration::from_secs(10), launcher.wait()).await {
        launcher_exit_code = status?.code();
    }

    let started_at = std::time::Instant::now();
    let mut remote_ids = BTreeSet::new();
    while started_at.elapsed() < timeout && !cancel.is_cancelled() {
        remote_ids = matching_remote_sessions_with_retry(&prepared.config, &prepared.root).await?;
        if !remote_ids.is_empty() {
            break;
        }
        time::sleep(Duration::from_secs(1)).await;
    }
    let remote_session_started = !remote_ids.is_empty();

    let mut timed_out = false;
    while remote_session_started && !remote_ids.is_empty() && !cancel.is_cancelled() {
        if started_at.elapsed() >= timeout {
            timed_out = true;
            break;
        }
        time::sleep(Duration::from_secs(5)).await;
        remote_ids = matching_remote_sessions_with_retry(&prepared.config, &prepared.root).await?;
    }
    let cancelled = cancel.is_cancelled();
    let mut cleanup_output = String::new();
    if !remote_ids.is_empty() && (cancelled || timed_out) {
        cleanup_output = terminate_remote_sessions(&remote_ids, &prepared.root).await?;
        remote_ids = matching_remote_sessions_with_retry(&prepared.config, &prepared.root).await?;
    }

    if launcher_exit_code.is_none() {
        launcher_exit_code = match time::timeout(Duration::from_secs(30), launcher.wait()).await {
            Ok(status) => status?.code(),
            Err(_) => {
                launcher.kill().await?;
                launcher.wait().await?.code()
            }
        };
    }
    let remote_session_closed = remote_ids.is_empty()
        && matching_remote_sessions_with_retry(&prepared.config, &prepared.root)
            .await?
            .is_empty();
    let success = remote_session_started
        && remote_session_closed
        && !timed_out
        && !cancelled
        && launcher_exit_code == Some(0);
    Ok(SandboxExecution {
        launcher_exit_code,
        remote_session_started,
        remote_session_closed,
        timed_out,
        cancelled,
        cleanup_output,
        success,
    })
}

async fn matching_remote_sessions(config: &Path, directory: &Path) -> Result<BTreeSet<u32>> {
    let system_root = std::env::var_os("SystemRoot").unwrap_or_default();
    let powershell =
        Path::new(&system_root).join(r"System32\WindowsPowerShell\v1.0\powershell.exe");
    let script = r#"$config = $env:AEGIS_SANDBOX_CONFIG; Get-CimInstance Win32_Process -Filter "Name = 'WindowsSandboxRemoteSession.exe'" | Where-Object { $_.CommandLine -and $_.CommandLine.Contains($config) } | ForEach-Object { $_.ProcessId }"#;
    let mut env = BTreeMap::new();
    env.insert(
        "AEGIS_SANDBOX_CONFIG".into(),
        config.to_string_lossy().into_owned(),
    );
    let output = crate::process::run(
        crate::process::ProcessSpec {
            program: powershell,
            args: vec![
                "-NoProfile".into(),
                "-NonInteractive".into(),
                "-Command".into(),
                script.into(),
            ],
            directory: directory.into(),
            env,
            timeout: Duration::from_secs(30),
        },
        CancellationToken::new(),
        |_| {},
    )
    .await?;
    ensure!(
        output.exit_code == Some(0) && !output.cancelled && !output.timed_out,
        "cannot query the Windows Sandbox remote session"
    );
    let mut ids = BTreeSet::new();
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        if let Ok(id) = line.trim().parse::<u32>() {
            ids.insert(id);
        }
    }
    Ok(ids)
}

async fn matching_remote_sessions_with_retry(
    config: &Path,
    directory: &Path,
) -> Result<BTreeSet<u32>> {
    let mut last_error = None;
    for attempt in 0..3 {
        match matching_remote_sessions(config, directory).await {
            Ok(ids) => return Ok(ids),
            Err(error) if attempt < 2 => {
                last_error = Some(error);
                time::sleep(Duration::from_secs(2)).await;
            }
            Err(error) => return Err(error),
        }
    }
    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("sandbox process query failed")))
}

async fn terminate_remote_sessions(ids: &BTreeSet<u32>, directory: &Path) -> Result<String> {
    let system_root = std::env::var_os("SystemRoot").unwrap_or_default();
    let taskkill = Path::new(&system_root).join(r"System32\taskkill.exe");
    let mut output = String::new();
    for id in ids {
        let result = crate::process::run(
            crate::process::ProcessSpec {
                program: taskkill.clone(),
                args: vec!["/PID".into(), id.to_string(), "/T".into(), "/F".into()],
                directory: directory.into(),
                env: BTreeMap::new(),
                timeout: Duration::from_secs(20),
            },
            CancellationToken::new(),
            |_| {},
        )
        .await?;
        output.push_str(&String::from_utf8_lossy(&result.stdout));
        output.push_str(&String::from_utf8_lossy(&result.stderr));
    }
    Ok(output.trim().into())
}

fn import_files(
    transfers: &[SandboxFileTransfer],
    destination_root: &Path,
) -> Result<Vec<SandboxArtifact>> {
    let mut artifacts = Vec::new();
    let mut seen = BTreeSet::new();
    for transfer in transfers {
        let relative = relative_path(&transfer.path)
            .with_context(|| format!("unsafe sandbox import path: {}", transfer.path))?;
        ensure!(
            seen.insert(relative.to_owned()),
            "duplicate sandbox import path"
        );
        let source = &transfer.source;
        ensure!(source.is_file(), "sandbox import is not a file: {source:?}");
        ensure!(
            !is_reparse_point(source),
            "sandbox import is a reparse point"
        );
        let destination = destination_root.join(relative);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        ensure!(
            !destination.exists(),
            "sandbox import destination already exists: {}",
            transfer.path
        );
        fs::copy(source, &destination)
            .with_context(|| format!("cannot copy sandbox file {}", transfer.path))?;
        artifacts.push(artifact(&destination, relative)?);
    }
    Ok(artifacts)
}

fn merge_artifacts(
    mut values: Vec<SandboxArtifact>,
    additional: SandboxArtifact,
) -> Vec<SandboxArtifact> {
    values.push(additional);
    values.sort_by(|left, right| left.path.cmp(&right.path));
    values
}

fn artifact(path: &Path, relative: &str) -> Result<SandboxArtifact> {
    let data = fs::read(path).with_context(|| format!("cannot read sandbox file {path:?}"))?;
    Ok(SandboxArtifact {
        path: relative.into(),
        sha256: aegis_domain::sha256(&data),
        size: data.len() as u64,
    })
}

fn write_json(path: &Path, value: &Value) -> Result<()> {
    let bytes = serde_json::to_vec_pretty(value)?;
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, &bytes)?;
    fs::rename(&temporary, path)?;
    Ok(())
}

fn sandbox_config(
    tools: &Path,
    input: &Path,
    output: &Path,
    memory_mb: u32,
    entrypoint: SandboxEntrypoint,
    mappings: &[SandboxMapping],
) -> Result<String> {
    let tools = absolute(tools)?;
    let input = absolute(input)?;
    let output = absolute(output)?;
    for path in [&tools, &input, &output] {
        ensure!(
            !is_reparse_point(path),
            "sandbox mapping may not be a reparse point"
        );
    }
    let mut mapped_lines = String::new();
    for mapping in mappings {
        ensure!(
            mapping.host.is_absolute() && !is_reparse_point(&mapping.host),
            "runtime mapping host must be absolute and not a reparse point"
        );
        mapped_lines.push_str(&mapped_folder(
            &mapping.host,
            &mapping.guest,
            mapping.read_only,
        )?);
        mapped_lines.push('\n');
    }
    Ok(format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <Networking>Disable</Networking>
  <vGPU>Disable</vGPU>
  <ClipboardRedirection>Disable</ClipboardRedirection>
  <PrinterRedirection>Disable</PrinterRedirection>
  <AudioInputRedirection>Disable</AudioInputRedirection>
  <VideoInputRedirection>Disable</VideoInputRedirection>
  <ProtectedClient>Enable</ProtectedClient>
  <MemoryInMB>{memory_mb}</MemoryInMB>
  <MappedFolders>
{}
{}
{}
{mapped_lines}
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -NoProfile -ExecutionPolicy Bypass -File {}\{} -InputPath {} -OutputPath {}</Command>
  </LogonCommand>
</Configuration>
"#,
        mapped_folder(&tools, GUEST_TOOLS, true)?,
        mapped_folder(&input, GUEST_INPUT, true)?,
        mapped_folder(&output, GUEST_OUTPUT, false)?,
        xml_escape(GUEST_TOOLS),
        xml_escape(entrypoint.guest_script()),
        xml_escape(GUEST_INPUT),
        xml_escape(GUEST_OUTPUT),
    ))
}

fn mapped_folder(host: &Path, guest: &str, read_only: bool) -> Result<String> {
    let host = absolute(host)?;
    let host = host.to_string_lossy();
    ensure!(
        !host.contains(['\n', '\r']),
        "sandbox host path contains an unsupported character"
    );
    Ok(format!(
        "    <MappedFolder>\n      <HostFolder>{}</HostFolder>\n      <SandboxFolder>{}</SandboxFolder>\n      <ReadOnly>{}</ReadOnly>\n    </MappedFolder>",
        xml_escape(&host),
        xml_escape(guest),
        if read_only { "true" } else { "false" }
    ))
}

fn absolute(path: &Path) -> Result<PathBuf> {
    ensure!(
        path.is_absolute(),
        "sandbox path must be absolute: {path:?}"
    );
    Ok(path.to_path_buf())
}

fn relative_path(path: &str) -> Option<&str> {
    (path.len() <= 512
        && !path.contains(['\\', ':', '\0', '\n', '\r'])
        && path
            .split('/')
            .all(|part| !part.is_empty() && part != "." && part != ".."))
    .then_some(path)
}

fn is_identifier(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
}

fn is_sha256(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn xml_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            other => escaped.push(other),
        }
    }
    escaped
}

#[cfg(windows)]
fn is_reparse_point(path: &Path) -> bool {
    use std::os::windows::fs::MetadataExt;
    fs::symlink_metadata(path)
        .map(|metadata| metadata.file_attributes() & 0x400 != 0)
        .unwrap_or(false)
}

#[cfg(not(windows))]
fn is_reparse_point(_path: &Path) -> bool {
    false
}
