//! A02 host/guest bridge for disposable Windows Sandbox attempts.
//!
//! The module deliberately does not expose a host command. Callers declare the
//! files to import, the fixed probe entrypoint is generated by this module, and
//! exported files are accepted only through a bounded receipt protocol.
use anyhow::{Context, Result, ensure};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Stdio,
    sync::OnceLock,
    time::Duration,
};
use tokio::{process::Command, sync::Mutex, time};
use tokio_util::sync::CancellationToken;

use crate::runtime::windows_runtime::{
    WindowsRuntimeAdapter, WindowsRuntimeConfig, WindowsRuntimeEntry, WindowsRuntimeMode,
};

pub const SANDBOX_SCHEMA_VERSION: u32 = 1;
pub const GUEST_TOOLS: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisTools";
pub const GUEST_INPUT: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisInput";
pub const GUEST_OUTPUT: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisOutput";
pub const GUEST_PYTHON: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisPython";
pub const GUEST_ZIG: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisZig";
pub const GUEST_TINYINST: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisTinyInst";
pub const GUEST_LLVM: &str = r"C:\Users\WDAGUtilityAccount\Desktop\AegisLLVM";
const RECEIPT_FILE: &str = "session.json";
const SESSION_RECOVERY_FILE: &str = "sandbox-session.json";

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum SandboxEntrypoint {
    #[serde(rename = "BOUNDARY_PROBE")]
    BoundaryProbe,
    #[serde(rename = "ORIGINAL_PE")]
    OriginalPe,
    #[serde(rename = "WINDOWS_PYTHON")]
    WindowsPython,
    #[serde(rename = "WINDOWS_NATIVE_SOURCE")]
    WindowsNativeSource,
    #[serde(rename = "TINY_INST_PE")]
    TinyInstPe,
    #[serde(rename = "LLVM_LIBFUZZER_PREBUILT")]
    LibFuzzerPrebuilt,
}

impl SandboxEntrypoint {
    fn guest_script(self) -> &'static str {
        match self {
            Self::BoundaryProbe => "probe.ps1",
            Self::OriginalPe => "run-pe.ps1",
            Self::WindowsPython => "run-python.ps1",
            Self::WindowsNativeSource => "run-native-source.ps1",
            Self::TinyInstPe => "run-tinyinst.ps1",
            Self::LibFuzzerPrebuilt => "run-libfuzzer.ps1",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxMapping {
    pub host: PathBuf,
    pub guest: String,
    pub read_only: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxSession {
    pub run_id: String,
    pub attempt_id: String,
    pub session_id: String,
    pub target_sha256: String,
    pub config_sha256: String,
    pub memory_mb: u32,
}

impl SandboxSession {
    pub fn validate(&self) -> Result<()> {
        for (name, value) in [
            ("run_id", &self.run_id),
            ("attempt_id", &self.attempt_id),
            ("session_id", &self.session_id),
        ] {
            ensure!(
                is_identifier(value),
                "{name} must contain 1-128 ASCII letters, digits, hyphens, or underscores"
            );
        }
        ensure!(
            self.session_id
                .starts_with(&format!("{}-", self.attempt_id)),
            "session_id must be namespaced by attempt_id"
        );
        ensure!(
            is_sha256(&self.target_sha256) && is_sha256(&self.config_sha256),
            "target and configuration hashes must be SHA-256 values"
        );
        ensure!(
            (2048..=8192).contains(&self.memory_mb),
            "memory_mb must be between 2048 and 8192"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxFileTransfer {
    pub source: PathBuf,
    pub path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxArtifact {
    pub path: String,
    pub sha256: String,
    pub size: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxReceipt {
    pub schema_version: u32,
    pub run_id: String,
    pub attempt_id: String,
    pub session_id: String,
    pub status: String,
}

impl SandboxReceipt {
    fn validate(&self, session: &SandboxSession) -> Result<()> {
        ensure!(
            self.schema_version == SANDBOX_SCHEMA_VERSION,
            "unsupported sandbox receipt schema"
        );
        ensure!(
            self.run_id == session.run_id
                && self.attempt_id == session.attempt_id
                && self.session_id == session.session_id,
            "sandbox receipt belongs to another attempt"
        );
        ensure!(
            ["COMPLETED", "ERROR"].contains(&self.status.as_str()),
            "sandbox receipt status must be COMPLETED or ERROR"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxOutputPolicy {
    pub required_files: BTreeSet<String>,
    pub optional_files: BTreeSet<String>,
    pub max_file_bytes: u64,
    pub max_total_bytes: u64,
}

impl SandboxOutputPolicy {
    pub fn probe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "output-marker.txt".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn original_pe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn windows_python() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn windows_native_source() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "compile.stderr.log".into(),
                "compile.stdout.log".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 4 * 1024 * 1024,
        }
    }

    pub fn tiny_inst_pe() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "coverage.txt".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "target-executed.txt".into(),
                "target.stderr.log".into(),
                "target.stdout.log".into(),
            ]),
            max_file_bytes: 1024 * 1024,
            max_total_bytes: 2 * 1024 * 1024,
        }
    }

    pub fn lib_fuzzer_prebuilt() -> Self {
        Self {
            required_files: BTreeSet::from([RECEIPT_FILE.into()]),
            optional_files: BTreeSet::from([
                "compile.stderr.log".into(),
                "compile.stdout.log".into(),
                "corpus.zip".into(),
                "crash-input.bin".into(),
                "fuzz-executed.txt".into(),
                "fuzzer.stderr.log".into(),
                "fuzzer.stdout.log".into(),
                "guest-error.json".into(),
                "guest-observation.json".into(),
                "replay.stderr.log".into(),
                "replay.stdout.log".into(),
            ]),
            max_file_bytes: 2 * 1024 * 1024,
            max_total_bytes: 8 * 1024 * 1024,
        }
    }

    fn allowed(&self, path: &str) -> bool {
        self.required_files.contains(path) || self.optional_files.contains(path)
    }

    fn validate(&self) -> Result<()> {
        ensure!(
            self.required_files.contains(RECEIPT_FILE),
            "the fixed export protocol requires session.json"
        );
        ensure!(
            self.required_files.is_disjoint(&self.optional_files),
            "required and optional output files overlap"
        );
        ensure!(
            self.max_file_bytes > 0
                && self.max_total_bytes >= self.max_file_bytes
                && self.max_total_bytes <= 64 * 1024 * 1024,
            "invalid sandbox output size policy"
        );
        for file in self.required_files.iter().chain(self.optional_files.iter()) {
            ensure!(
                relative_path(file).is_some(),
                "invalid output file path: {file}"
            );
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxOutput {
    pub receipt: SandboxReceipt,
    pub artifacts: Vec<SandboxArtifact>,
    pub total_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxExecution {
    pub start_exit_code: Option<i32>,
    pub guest_exit_code: Option<i32>,
    pub stop_exit_code: Option<i32>,
    pub session_id: String,
    pub remote_session_started: bool,
    pub remote_session_closed: bool,
    pub timed_out: bool,
    pub cancelled: bool,
    pub cleanup_output: String,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxSessionRecord {
    pub schema_version: u32,
    pub session: SandboxSession,
    pub wsb_session_id: String,
    pub machine_identity: String,
    pub closed: bool,
}

impl SandboxSessionRecord {
    fn validate(&self) -> Result<()> {
        ensure!(
            self.schema_version == SANDBOX_SCHEMA_VERSION,
            "unsupported sandbox recovery schema"
        );
        self.session.validate()?;
        ensure!(
            is_identifier(&self.wsb_session_id),
            "invalid Windows Sandbox environment id"
        );
        ensure!(
            !self.machine_identity.is_empty()
                && self.machine_identity.bytes().all(|b| b.is_ascii_hexdigit()),
            "invalid sandbox machine identity"
        );
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SandboxRecoveryProof {
    pub session_id: String,
    pub remote_session_closed: bool,
    pub stop_exit_code: Option<i32>,
    pub cleanup_output: String,
    pub machine_verified: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreparedSandbox {
    pub entrypoint: SandboxEntrypoint,
    pub session: SandboxSession,
    pub root: PathBuf,
    pub input: PathBuf,
    pub output: PathBuf,
    pub tools: PathBuf,
    pub config: PathBuf,
    pub manifest: PathBuf,
    pub input_files: Vec<SandboxArtifact>,
    pub tool_files: Vec<SandboxArtifact>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SandboxSpec {
    pub entrypoint: SandboxEntrypoint,
    pub session: SandboxSession,
    pub root: PathBuf,
    pub inputs: Vec<SandboxFileTransfer>,
    pub tools: Vec<SandboxFileTransfer>,
    #[serde(default)]
    pub mappings: Vec<SandboxMapping>,
    pub runtime_config: Option<WindowsRuntimeConfig>,
}

pub fn prepare(spec: &SandboxSpec) -> Result<PreparedSandbox> {
    spec.session.validate()?;
    let runtime_config = match (&spec.entrypoint, &spec.runtime_config) {
        (SandboxEntrypoint::BoundaryProbe, None) => None,
        (SandboxEntrypoint::OriginalPe, Some(config)) => {
            config.validate()?;
            ensure!(
                matches!(
                    config.adapter,
                    WindowsRuntimeAdapter::OriginalPe32 | WindowsRuntimeAdapter::OriginalPe64
                ),
                "the original PE entrypoint requires a PE adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the original PE entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the original PE entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            Some(config)
        }
        (SandboxEntrypoint::BoundaryProbe, Some(_)) => {
            return Err(anyhow::anyhow!(
                "the boundary probe does not accept a runtime configuration"
            ));
        }
        (SandboxEntrypoint::OriginalPe, None) => {
            return Err(anyhow::anyhow!(
                "the original PE entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::WindowsPython, Some(config)) => {
            config.validate()?;
            ensure!(
                config.adapter == WindowsRuntimeAdapter::PythonCall,
                "the Windows Python entrypoint requires the Python adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::Function { .. }),
                "the Windows Python entrypoint requires a function entry"
            );
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_PYTHON
                        && mapping.read_only
                        && mapping.host.join("python.exe").is_file()
                }),
                "the Windows Python entrypoint requires a read-only Python runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::WindowsPython, None) => {
            return Err(anyhow::anyhow!(
                "the Windows Python entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::WindowsNativeSource, Some(config)) => {
            config.validate()?;
            ensure!(
                config.adapter == WindowsRuntimeAdapter::NativeSource,
                "the native-source entrypoint requires the native-source adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the native-source entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the native-source entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_ZIG
                        && mapping.read_only
                        && mapping.host.join("zig.exe").is_file()
                }),
                "the native-source entrypoint requires a read-only Zig runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::WindowsNativeSource, None) => {
            return Err(anyhow::anyhow!(
                "the native-source entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::TinyInstPe, Some(config)) => {
            config.validate()?;
            ensure!(
                matches!(
                    config.adapter,
                    WindowsRuntimeAdapter::OriginalPe32 | WindowsRuntimeAdapter::OriginalPe64
                ),
                "the TinyInst entrypoint requires a PE adapter"
            );
            ensure!(
                matches!(&config.entry, WindowsRuntimeEntry::CommandLine { .. }),
                "the TinyInst entrypoint requires a command-line entry"
            );
            if let WindowsRuntimeEntry::CommandLine { path, .. } = &config.entry {
                ensure!(
                    path == &config.target_path,
                    "the TinyInst entry must execute the declared target"
                );
            }
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_TINYINST
                        && mapping.read_only
                        && mapping.host.join("litecov.exe").is_file()
                }),
                "the TinyInst entrypoint requires a read-only TinyInst runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::TinyInstPe, None) => {
            return Err(anyhow::anyhow!(
                "the TinyInst entrypoint requires a runtime configuration"
            ));
        }
        (SandboxEntrypoint::LibFuzzerPrebuilt, Some(config)) => {
            config.validate()?;
            ensure!(
                config.mode == WindowsRuntimeMode::Fuzz,
                "the libFuzzer entrypoint requires FUZZ mode"
            );
            ensure!(
                config.adapter == WindowsRuntimeAdapter::LibFuzzerPrebuilt,
                "the libFuzzer entrypoint requires the prebuilt libFuzzer adapter"
            );
            ensure!(
                config.fingerprint()? == spec.session.config_sha256,
                "the sandbox session and runtime configuration hashes disagree"
            );
            ensure!(
                spec.mappings.iter().any(|mapping| {
                    mapping.guest == GUEST_LLVM
                        && mapping.read_only
                        && mapping.host.join("bin/clang.exe").is_file()
                }),
                "the libFuzzer entrypoint requires a read-only LLVM runtime mapping"
            );
            Some(config)
        }
        (SandboxEntrypoint::LibFuzzerPrebuilt, None) => {
            return Err(anyhow::anyhow!(
                "the libFuzzer entrypoint requires a runtime configuration"
            ));
        }
    };
    for mapping in &spec.mappings {
        ensure!(
            mapping.host.is_absolute() && mapping.host.is_dir() && !is_reparse_point(&mapping.host),
            "sandbox mapping host must be an absolute directory"
        );
        ensure!(
            (mapping.guest == GUEST_PYTHON
                || mapping.guest == GUEST_ZIG
                || mapping.guest == GUEST_TINYINST
                || mapping.guest == GUEST_LLVM)
                && mapping.read_only,
            "only fixed read-only Python, Zig, TinyInst, and LLVM mappings are currently supported"
        );
        ensure!(
            mapping.host != spec.root.join("input")
                && mapping.host != spec.root.join("output")
                && mapping.host != spec.root.join("tools"),
            "runtime mapping may not overlap attempt directories"
        );
    }
    ensure!(
        spec.inputs.len() <= 256 && spec.tools.len() <= 128,
        "a sandbox attempt may import at most 256 inputs and 128 tools"
    );
    if spec.root.exists() {
        ensure!(spec.root.is_dir(), "sandbox root is not a directory");
        ensure!(
            fs::read_dir(&spec.root)?.next().is_none(),
            "sandbox root must be empty so outputs cannot belong to an older attempt"
        );
    } else {
        fs::create_dir_all(&spec.root)?;
    }
    ensure!(
        !is_reparse_point(&spec.root),
        "sandbox root may not be a reparse point"
    );
    let input = spec.root.join("input");
    let output = spec.root.join("output");
    let tools = spec.root.join("tools");
    for directory in [&input, &output, &tools] {
        fs::create_dir(directory)?;
        ensure!(
            !is_reparse_point(directory),
            "sandbox directory may not be a reparse point"
        );
    }

    let input_files = import_files(&spec.inputs, &input)?;
    let tool_files = import_files(&spec.tools, &tools)?;
    ensure!(
        tool_files
            .iter()
            .any(|item| item.path == spec.entrypoint.guest_script()),
        "the sandbox tool set is missing its fixed entrypoint"
    );
    write_json(
        &input.join(RECEIPT_FILE),
        &json!({
            "schema_version": SANDBOX_SCHEMA_VERSION,
            "run_id": spec.session.run_id,
            "attempt_id": spec.session.attempt_id,
            "session_id": spec.session.session_id,
            "target_sha256": spec.session.target_sha256,
            "config_sha256": spec.session.config_sha256
        }),
    )?;
    let receipt_artifact = artifact(&input.join(RECEIPT_FILE), RECEIPT_FILE)?;
    let input_files = merge_artifacts(input_files, receipt_artifact);
    let input_files = if let Some(runtime_config) = runtime_config {
        let runtime_path = input.join("runtime-config.json");
        write_json(&runtime_path, &serde_json::to_value(runtime_config)?)?;
        let runtime_artifact = artifact(&runtime_path, "runtime-config.json")?;
        merge_artifacts(input_files, runtime_artifact)
    } else {
        input_files
    };
    ensure!(
        input_files
            .iter()
            .any(|item| item.sha256 == spec.session.target_sha256),
        "the imported input set must contain the declared target hash"
    );
    if let Some(runtime_config) = runtime_config {
        ensure!(
            input_files
                .iter()
                .any(|item| item.path == runtime_config.target_path
                    && item.sha256 == runtime_config.target_sha256),
            "the imported input set must contain the declared runtime target"
        );
    }

    let manifest = spec.root.join("host-manifest.json");
    write_json(
        &manifest,
        &json!({
            "schema_version": SANDBOX_SCHEMA_VERSION,
            "session": spec.session,
            "guest_paths": {
                "tools": GUEST_TOOLS,
                "input": GUEST_INPUT,
                "output": GUEST_OUTPUT
            },
            "policy": {
                "networking": "DISABLED",
                "v_gpu": "DISABLED",
                "clipboard_redirection": "DISABLED",
                "printer_redirection": "DISABLED",
                "audio_input_redirection": "DISABLED",
                "video_input_redirection": "DISABLED",
                "protected_client": "ENABLED",
                "memory_mb": spec.session.memory_mb,
                "input_read_only": true,
                "output_read_only": false
            },
            "input_files": input_files,
            "tool_files": tool_files,
            "entrypoint": spec.entrypoint,
            "mappings": spec.mappings
        }),
    )?;
    let config = spec.root.join("sandbox.wsb");
    fs::write(
        &config,
        sandbox_config(
            &tools,
            &input,
            &output,
            spec.session.memory_mb,
            spec.entrypoint,
            &spec.mappings,
        )?,
    )?;
    Ok(PreparedSandbox {
        entrypoint: spec.entrypoint,
        session: spec.session.clone(),
        root: spec.root.clone(),
        input,
        output,
        tools,
        config,
        manifest,
        input_files,
        tool_files,
    })
}

pub fn verify_inputs(prepared: &PreparedSandbox) -> Result<()> {
    for (base, expected) in prepared
        .input_files
        .iter()
        .map(|expected| (&prepared.input, expected))
        .chain(
            prepared
                .tool_files
                .iter()
                .map(|expected| (&prepared.tools, expected)),
        )
    {
        let path = base.join(&expected.path);
        ensure!(
            path.is_file(),
            "sandbox input is missing: {}",
            expected.path
        );
        ensure!(!is_reparse_point(&path), "sandbox input is a reparse point");
        let actual = artifact(&path, &expected.path)?;
        ensure!(
            actual == *expected,
            "sandbox input changed after preparation: {}",
            expected.path
        );
    }
    Ok(())
}

pub fn collect_output(
    prepared: &PreparedSandbox,
    policy: &SandboxOutputPolicy,
) -> Result<SandboxOutput> {
    policy.validate()?;
    ensure!(
        prepared.output.is_dir() && !is_reparse_point(&prepared.output),
        "sandbox output directory is missing or unsafe"
    );
    let mut artifacts = Vec::new();
    let mut total_bytes = 0u64;
    for entry in fs::read_dir(&prepared.output)? {
        let entry = entry?;
        let path = entry.path();
        ensure!(path.is_file(), "sandbox output must contain files only");
        ensure!(
            !is_reparse_point(&path),
            "sandbox output is a reparse point"
        );
        let relative = path
            .strip_prefix(&prepared.output)
            .map_err(|_| anyhow::anyhow!("output path escapes its directory"))?
            .to_string_lossy()
            .replace('\\', "/");
        ensure!(
            policy.allowed(&relative),
            "sandbox output is not allowed by the export policy: {relative}"
        );
        let artifact = artifact(&path, &relative)?;
        ensure!(
            artifact.size <= policy.max_file_bytes,
            "sandbox output exceeds the per-file limit: {relative}"
        );
        total_bytes = total_bytes
            .checked_add(artifact.size)
            .ok_or_else(|| anyhow::anyhow!("sandbox output size overflow"))?;
        artifacts.push(artifact);
    }
    ensure!(
        total_bytes <= policy.max_total_bytes,
        "sandbox output exceeds the total size limit"
    );
    let actual: BTreeSet<_> = artifacts.iter().map(|item| item.path.as_str()).collect();
    for required in &policy.required_files {
        ensure!(
            actual.contains(required.as_str()),
            "required sandbox output is missing: {required}"
        );
    }
    let receipt_path = prepared.output.join(RECEIPT_FILE);
    let receipt_text = fs::read_to_string(&receipt_path)
        .with_context(|| format!("cannot read sandbox receipt {receipt_path:?}"))?;
    let receipt: SandboxReceipt = serde_json::from_str(receipt_text.trim_start_matches('\u{feff}'))
        .with_context(|| format!("invalid sandbox receipt {receipt_path:?}"))?;
    receipt.validate(&prepared.session)?;
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(SandboxOutput {
        receipt,
        artifacts,
        total_bytes,
    })
}

pub async fn run_probe(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::BoundaryProbe,
        "run_probe is only for the harmless boundary probe"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_original_pe(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::OriginalPe,
        "run_original_pe is only for declared original PE attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_windows_python(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::WindowsPython,
        "run_windows_python is only for declared Windows Python attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_native_source(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::WindowsNativeSource,
        "run_native_source is only for declared native-source attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_tinyinst(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::TinyInstPe,
        "run_tinyinst is only for declared TinyInst PE attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

pub async fn run_libfuzzer(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    ensure!(
        prepared.entrypoint == SandboxEntrypoint::LibFuzzerPrebuilt,
        "run_libfuzzer is only for declared prebuilt libFuzzer attempts"
    );
    run_sandbox(prepared, timeout, cancel).await
}

async fn run_sandbox(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    let _global_gate = acquire_global_sandbox_gate(cancel.clone()).await?;
    static SANDBOX_GATE: OnceLock<Mutex<()>> = OnceLock::new();
    let gate = SANDBOX_GATE.get_or_init(|| Mutex::new(()));
    let _sandbox_gate = gate.lock().await;
    run_sandbox_locked(prepared, timeout, cancel).await
}

#[cfg(windows)]
struct GlobalSandboxGuard(usize);

#[cfg(windows)]
impl Drop for GlobalSandboxGuard {
    fn drop(&mut self) {
        use windows_sys::Win32::Foundation::CloseHandle;
        use windows_sys::Win32::System::Threading::ReleaseMutex;

        let handle = self.0 as windows_sys::Win32::Foundation::HANDLE;
        unsafe {
            ReleaseMutex(handle);
            CloseHandle(handle);
        }
    }
}

#[cfg(windows)]
async fn acquire_global_sandbox_gate(cancel: CancellationToken) -> Result<GlobalSandboxGuard> {
    tokio::task::spawn_blocking(move || {
        use windows_sys::Win32::Foundation::CloseHandle;
        use windows_sys::Win32::System::Threading::{CreateMutexW, WaitForSingleObject};

        fn acquire(name: &str, cancel: &CancellationToken) -> Result<GlobalSandboxGuard> {
            let wide: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
            let handle = unsafe { CreateMutexW(std::ptr::null(), 0, wide.as_ptr()) };
            ensure!(
                !handle.is_null(),
                "cannot create the Windows Sandbox global mutex"
            );
            loop {
                let wait = unsafe { WaitForSingleObject(handle, 1_000) };
                if wait == 0 || wait == 0x80 {
                    return Ok(GlobalSandboxGuard(handle as usize));
                }
                if cancel.is_cancelled() {
                    unsafe { CloseHandle(handle) };
                    anyhow::bail!("cancelled while waiting for the Windows Sandbox global mutex");
                }
                if wait != 258 {
                    unsafe { CloseHandle(handle) };
                    anyhow::bail!("Windows Sandbox global mutex wait failed: {wait}");
                }
            }
        }

        acquire("Global\\AegisAudit-Windows-Sandbox-Runner", &cancel).or_else(|error| {
            acquire("Local\\AegisAudit-Windows-Sandbox-Runner", &cancel)
                .map_err(|local_error| error.context(local_error))
        })
    })
    .await?
}

#[cfg(not(windows))]
async fn acquire_global_sandbox_gate(_cancel: CancellationToken) -> Result<()> {
    Ok(())
}

async fn run_sandbox_locked(
    prepared: &PreparedSandbox,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<SandboxExecution> {
    let wsb = locate_wsb()?;
    let config_text = fs::read_to_string(&prepared.config)?;
    let pre_start_ids =
        list_environment_ids(&wsb, &prepared.root, "sandbox-list-before-start.json").await?;

    let start = match start_wsb(&wsb, &config_text, cancel.clone(), &prepared.root).await {
        Ok(start) => start,
        Err(error) => {
            let _ = stop_new_environments(&wsb, &prepared.root, &pre_start_ids).await;
            return Err(error);
        }
    };
    write_wsb_log(&prepared.root, "sandbox-start.json", &start)?;
    let parsed_start = if start.exit_code == Some(0) && !start.timed_out && !start.cancelled {
        serde_json::from_slice::<Value>(&start.stdout)
            .context("invalid wsb start output")
            .and_then(|value| {
                value["Id"]
                    .as_str()
                    .map(str::to_owned)
                    .context("wsb start did not return a sandbox ID")
            })
    } else {
        Err(anyhow::anyhow!(
            "wsb start failed: {}{}",
            String::from_utf8_lossy(&start.stdout),
            String::from_utf8_lossy(&start.stderr)
        ))
    };
    let session_id = match parsed_start {
        Ok(session_id) => session_id,
        Err(error) => {
            let _ = stop_new_environments(&wsb, &prepared.root, &pre_start_ids).await;
            return Err(error);
        }
    };
    let remote_session_started = !session_id.is_empty();
    if let Err(error) =
        write_session_recovery(&prepared.root, &prepared.session, &session_id, false)
    {
        let cleanup = stop_wsb_session(&wsb, &prepared.root, &session_id, "sandbox-start-cleanup")
            .await
            .err()
            .map(|cleanup_error| cleanup_error.to_string())
            .unwrap_or_else(|| "cleanup command completed".into());
        return Err(error.context(format!(
            "cannot persist sandbox ownership before guest execution: {cleanup}"
        )));
    }

    let mut failures: Vec<anyhow::Error> = Vec::new();

    let guest_command = format!(
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -File {}\\{} -InputPath {} -OutputPath {}",
        GUEST_TOOLS,
        prepared.entrypoint.guest_script(),
        GUEST_INPUT,
        GUEST_OUTPUT
    );
    let mut exec_command = Command::new(&wsb);
    exec_command
        .arg("exec")
        .arg("--raw")
        .arg("--id")
        .arg(&session_id)
        .arg("-r")
        .arg("System")
        .arg("-c")
        .arg(&guest_command);
    let exec = match run_wsb_command(&mut exec_command, timeout, cancel.clone()).await {
        Ok(exec) => exec,
        Err(error) => {
            failures.push(error);
            WsbCommandOutput {
                exit_code: None,
                stdout: Vec::new(),
                stderr: Vec::new(),
                timed_out: false,
                cancelled: cancel.is_cancelled(),
            }
        }
    };
    if let Err(error) = write_wsb_log(&prepared.root, "sandbox-exec.json", &exec) {
        failures.push(error);
    }
    let exec_value = if exec.stdout.is_empty() {
        Value::Null
    } else {
        match serde_json::from_slice(&exec.stdout) {
            Ok(value) => value,
            Err(error) => {
                failures.push(error.into());
                Value::Null
            }
        }
    };
    let guest_exit_code = exec_value["ExitCode"].as_i64().map(|code| code as i32);
    if !((exec.exit_code == Some(0) || guest_exit_code.is_some())
        || exec.timed_out
        || exec.cancelled)
    {
        failures.push(anyhow::anyhow!(
            "wsb exec failed: {}{}",
            String::from_utf8_lossy(&exec.stdout),
            String::from_utf8_lossy(&exec.stderr)
        ));
    }

    let mut list_command = Command::new(&wsb);
    list_command.arg("list").arg("--raw");
    let before_stop = match run_wsb_command(
        &mut list_command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await
    {
        Ok(output) => Some(output),
        Err(error) => {
            failures.push(error);
            None
        }
    };
    if let Some(before_stop) = &before_stop {
        let log_result =
            write_wsb_log(&prepared.root, "sandbox-list-before-stop.json", before_stop);
        if let Err(error) = log_result {
            failures.push(error);
        }
    }
    let still_running = before_stop
        .as_ref()
        .and_then(|output| session_is_listed(&output.stdout, &session_id).ok())
        .unwrap_or(true);

    let mut stop_exit_code = None;
    let mut cleanup_output = String::new();
    if still_running {
        match stop_wsb_session(&wsb, &prepared.root, &session_id, "sandbox-stop.json").await {
            Ok((exit_code, output)) => {
                stop_exit_code = exit_code;
                cleanup_output = output;
            }
            Err(error) => failures.push(error),
        }
    }

    let mut final_list_command = Command::new(&wsb);
    final_list_command.arg("list").arg("--raw");
    let after_stop = match run_wsb_command(
        &mut final_list_command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await
    {
        Ok(output) => Some(output),
        Err(error) => {
            failures.push(error);
            None
        }
    };
    let mut remote_session_closed = false;
    if let Some(after_stop) = &after_stop {
        if let Err(error) =
            write_wsb_log(&prepared.root, "sandbox-list-after-stop.json", after_stop)
        {
            failures.push(error);
        }
        match session_is_listed(&after_stop.stdout, &session_id) {
            Ok(listed) => remote_session_closed = !listed,
            Err(error) => failures.push(error),
        }
    }

    if let Err(error) = write_session_recovery(&prepared.root, &prepared.session, &session_id, true)
    {
        failures.push(error);
    }

    let timed_out = exec.timed_out;
    let cancelled = exec.cancelled || cancel.is_cancelled();
    let success = remote_session_started
        && remote_session_closed
        && guest_exit_code == Some(0)
        && !timed_out
        && !cancelled
        && (stop_exit_code.is_none() || stop_exit_code == Some(0));
    let execution = SandboxExecution {
        start_exit_code: start.exit_code,
        guest_exit_code,
        stop_exit_code,
        session_id,
        remote_session_started,
        remote_session_closed,
        timed_out,
        cancelled,
        cleanup_output,
        success,
    };
    if let Some(error) = failures.into_iter().next() {
        return Err(error.context(format!(
            "Windows Sandbox attempt failed after cleanup: {execution:?}"
        )));
    }
    Ok(execution)
}

/// Recover an attempt-specific Windows Sandbox session after its executor died.
///
/// The recovery record is written before guest execution and only after the host
/// has confirmed that the WSB environment is gone. This prevents a new runtime
/// attempt from being started while an unowned environment still exists.
pub async fn recover_session(root: &Path) -> Result<Option<SandboxRecoveryProof>> {
    let record_path = root.join(SESSION_RECOVERY_FILE);
    if !record_path.is_file() {
        return Ok(None);
    }
    let record: SandboxSessionRecord = serde_json::from_slice(&fs::read(&record_path)?)
        .with_context(|| format!("invalid sandbox recovery record {record_path:?}"))?;
    record.validate()?;
    ensure!(
        record.machine_identity == crate::windows_job::machine_identity()?,
        "sandbox recovery record belongs to a different Windows machine"
    );
    if record.closed {
        return Ok(None);
    }

    let wsb = locate_wsb()?;
    let mut list_command = Command::new(&wsb);
    list_command.arg("list").arg("--raw");
    let initial = run_wsb_command(
        &mut list_command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await?;
    write_wsb_log(root, "sandbox-recovery-list-before-stop.json", &initial)?;
    if !session_is_listed(&initial.stdout, &record.wsb_session_id)? {
        let mut recovered = record.clone();
        recovered.closed = true;
        write_recovery_record(root, &recovered)?;
        return Ok(Some(SandboxRecoveryProof {
            session_id: record.wsb_session_id,
            remote_session_closed: true,
            stop_exit_code: None,
            cleanup_output: String::new(),
            machine_verified: true,
        }));
    }

    let (stop_exit_code, cleanup_output) = stop_wsb_session(
        &wsb,
        root,
        &record.wsb_session_id,
        "sandbox-recovery-stop.json",
    )
    .await?;
    let mut final_list_command = Command::new(&wsb);
    final_list_command.arg("list").arg("--raw");
    let final_list = run_wsb_command(
        &mut final_list_command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await?;
    write_wsb_log(root, "sandbox-recovery-list-after-stop.json", &final_list)?;
    let remote_session_closed = !session_is_listed(&final_list.stdout, &record.wsb_session_id)?;
    ensure!(
        remote_session_closed,
        "owned Windows Sandbox session did not close after executor recovery: {}{}",
        String::from_utf8_lossy(&final_list.stdout),
        String::from_utf8_lossy(&final_list.stderr)
    );
    let mut recovered = record.clone();
    recovered.closed = true;
    write_recovery_record(root, &recovered)?;
    Ok(Some(SandboxRecoveryProof {
        session_id: record.wsb_session_id,
        remote_session_closed,
        stop_exit_code,
        cleanup_output,
        machine_verified: true,
    }))
}

async fn list_environment_ids(wsb: &Path, root: &Path, log_name: &str) -> Result<BTreeSet<String>> {
    let mut command = Command::new(wsb);
    command.arg("list").arg("--raw");
    let output = run_wsb_command(
        &mut command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await?;
    write_wsb_log(root, log_name, &output)?;
    let value: Value = serde_json::from_slice(&output.stdout).context("invalid wsb list output")?;
    let items = value["WindowsSandboxEnvironments"]
        .as_array()
        .context("wsb list output is missing WindowsSandboxEnvironments")?;
    let mut ids = BTreeSet::new();
    for item in items {
        let id = item["Id"]
            .as_str()
            .context("wsb list output contains an environment without an id")?;
        ensure!(!id.is_empty(), "wsb list output contains an empty id");
        ids.insert(id.to_owned());
    }
    Ok(ids)
}

async fn stop_new_environments(
    wsb: &Path,
    root: &Path,
    previous_ids: &BTreeSet<String>,
) -> Result<Vec<String>> {
    let current_ids =
        list_environment_ids(wsb, root, "sandbox-start-recovery-list-before-stop.json").await?;
    let new_ids: Vec<_> = current_ids.difference(previous_ids).cloned().collect();
    for id in &new_ids {
        stop_wsb_session(
            wsb,
            root,
            id,
            &format!("sandbox-start-recovery-stop-{id}.json"),
        )
        .await?;
    }
    if !new_ids.is_empty() {
        list_environment_ids(wsb, root, "sandbox-start-recovery-list-after-stop.json").await?;
    }
    Ok(new_ids)
}

fn session_is_listed(stdout: &[u8], session_id: &str) -> Result<bool> {
    let value: Value = serde_json::from_slice(stdout).context("invalid wsb list output")?;
    let items = value["WindowsSandboxEnvironments"]
        .as_array()
        .context("wsb list output is missing WindowsSandboxEnvironments")?;
    Ok(items
        .iter()
        .any(|item| item["Id"].as_str() == Some(session_id)))
}

async fn stop_wsb_session(
    wsb: &Path,
    root: &Path,
    session_id: &str,
    log_name: &str,
) -> Result<(Option<i32>, String)> {
    let mut stop_command = Command::new(wsb);
    stop_command
        .arg("stop")
        .arg("--raw")
        .arg("--id")
        .arg(session_id);
    let stop = run_wsb_command(
        &mut stop_command,
        Duration::from_secs(30),
        CancellationToken::new(),
    )
    .await?;
    write_wsb_log(root, log_name, &stop)?;
    let mut cleanup_output = String::new();
    cleanup_output.push_str(&String::from_utf8_lossy(&stop.stdout));
    cleanup_output.push_str(&String::from_utf8_lossy(&stop.stderr));
    Ok((stop.exit_code, cleanup_output))
}

fn write_session_recovery(
    root: &Path,
    session: &SandboxSession,
    wsb_session_id: &str,
    closed: bool,
) -> Result<()> {
    let record = SandboxSessionRecord {
        schema_version: SANDBOX_SCHEMA_VERSION,
        session: session.clone(),
        wsb_session_id: wsb_session_id.into(),
        machine_identity: crate::windows_job::machine_identity()?,
        closed,
    };
    record.validate()?;
    write_recovery_record(root, &record)
}

fn write_recovery_record(root: &Path, record: &SandboxSessionRecord) -> Result<()> {
    record.validate()?;
    fs::write(
        root.join(SESSION_RECOVERY_FILE),
        serde_json::to_vec_pretty(record)?,
    )?;
    Ok(())
}

async fn start_wsb(
    wsb: &Path,
    config_text: &str,
    cancel: CancellationToken,
    root: &Path,
) -> Result<WsbCommandOutput> {
    let mut last_message = String::new();
    for attempt in 1..=30 {
        let mut command = Command::new(wsb);
        command
            .arg("start")
            .arg("--raw")
            .arg("--config")
            .arg(config_text);
        let output = run_wsb_command(&mut command, Duration::from_secs(60), cancel.clone()).await?;
        write_wsb_log(
            root,
            &format!("sandbox-start-attempt-{attempt}.json"),
            &output,
        )?;
        if output.exit_code == Some(0) && !output.timed_out && !output.cancelled {
            return Ok(output);
        }
        let message = format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        let single_use =
            message.contains("CO_E_APPSINGLEUSE") || message.contains("应用程序无法多次运行");
        last_message = message;
        if !single_use || cancel.is_cancelled() {
            break;
        }
        time::sleep(Duration::from_secs(2)).await;
    }
    Err(anyhow::anyhow!("wsb start failed: {last_message}"))
}

#[derive(Debug)]
struct WsbCommandOutput {
    exit_code: Option<i32>,
    stdout: Vec<u8>,
    stderr: Vec<u8>,
    timed_out: bool,
    cancelled: bool,
}

async fn run_wsb_command(
    command: &mut Command,
    timeout: Duration,
    cancel: CancellationToken,
) -> Result<WsbCommandOutput> {
    command
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true);
    let child = command.spawn()?;
    let mut timed_out = false;
    let mut cancelled = false;
    let output = tokio::select! {
        output = child.wait_with_output() => Some(output?),
        _ = time::sleep(timeout) => {
            timed_out = true;
            None
        }
        _ = cancel.cancelled() => {
            cancelled = true;
            None
        }
    };
    let (exit_code, stdout, stderr) = match output {
        Some(output) => (output.status.code(), output.stdout, output.stderr),
        None => (None, Vec::new(), Vec::new()),
    };
    Ok(WsbCommandOutput {
        exit_code,
        stdout,
        stderr,
        timed_out,
        cancelled,
    })
}

fn write_wsb_log(root: &Path, name: &str, output: &WsbCommandOutput) -> Result<()> {
    let value = json!({
        "exit_code": output.exit_code,
        "stdout": String::from_utf8_lossy(&output.stdout),
        "stderr": String::from_utf8_lossy(&output.stderr),
        "timed_out": output.timed_out,
        "cancelled": output.cancelled,
    });
    let bytes = serde_json::to_vec_pretty(&value)?;
    fs::write(root.join(name), bytes)?;
    Ok(())
}

fn locate_wsb() -> Result<PathBuf> {
    if let Some(local_app_data) = std::env::var_os("LOCALAPPDATA") {
        let candidate = Path::new(&local_app_data).join(r"Microsoft\WindowsApps\wsb.exe");
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    if let Some(path) = std::env::var_os("PATH") {
        for directory in std::env::split_paths(&path) {
            let candidate = directory.join("wsb.exe");
            if candidate.is_file() {
                return Ok(candidate);
            }
        }
    }
    anyhow::bail!("Windows Sandbox CLI (wsb.exe) is unavailable")
}

fn import_files(
    transfers: &[SandboxFileTransfer],
    destination_root: &Path,
) -> Result<Vec<SandboxArtifact>> {
    let mut artifacts = Vec::new();
    let mut seen = BTreeSet::new();
    for transfer in transfers {
        let relative = relative_path(&transfer.path)
            .with_context(|| format!("unsafe sandbox import path: {}", transfer.path))?;
        ensure!(
            seen.insert(relative.to_owned()),
            "duplicate sandbox import path"
        );
        let source = &transfer.source;
        ensure!(source.is_file(), "sandbox import is not a file: {source:?}");
        ensure!(
            !is_reparse_point(source),
            "sandbox import is a reparse point"
        );
        let destination = destination_root.join(relative);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        ensure!(
            !destination.exists(),
            "sandbox import destination already exists: {}",
            transfer.path
        );
        fs::copy(source, &destination)
            .with_context(|| format!("cannot copy sandbox file {}", transfer.path))?;
        artifacts.push(artifact(&destination, relative)?);
    }
    Ok(artifacts)
}

fn merge_artifacts(
    mut values: Vec<SandboxArtifact>,
    additional: SandboxArtifact,
) -> Vec<SandboxArtifact> {
    values.push(additional);
    values.sort_by(|left, right| left.path.cmp(&right.path));
    values
}

fn artifact(path: &Path, relative: &str) -> Result<SandboxArtifact> {
    let data = fs::read(path).with_context(|| format!("cannot read sandbox file {path:?}"))?;
    Ok(SandboxArtifact {
        path: relative.into(),
        sha256: aegis_domain::sha256(&data),
        size: data.len() as u64,
    })
}

fn write_json(path: &Path, value: &Value) -> Result<()> {
    let bytes = serde_json::to_vec_pretty(value)?;
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, &bytes)?;
    fs::rename(&temporary, path)?;
    Ok(())
}

fn sandbox_config(
    tools: &Path,
    input: &Path,
    output: &Path,
    memory_mb: u32,
    entrypoint: SandboxEntrypoint,
    mappings: &[SandboxMapping],
) -> Result<String> {
    let tools = absolute(tools)?;
    let input = absolute(input)?;
    let output = absolute(output)?;
    for path in [&tools, &input, &output] {
        ensure!(
            !is_reparse_point(path),
            "sandbox mapping may not be a reparse point"
        );
    }
    let mut mapped_lines = String::new();
    for mapping in mappings {
        ensure!(
            mapping.host.is_absolute() && !is_reparse_point(&mapping.host),
            "runtime mapping host must be absolute and not a reparse point"
        );
        mapped_lines.push_str(&mapped_folder(
            &mapping.host,
            &mapping.guest,
            mapping.read_only,
        )?);
        mapped_lines.push('\n');
    }
    Ok(format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <Networking>Disable</Networking>
  <vGPU>Disable</vGPU>
  <ClipboardRedirection>Disable</ClipboardRedirection>
  <PrinterRedirection>Disable</PrinterRedirection>
  <AudioInputRedirection>Disable</AudioInputRedirection>
  <VideoInputRedirection>Disable</VideoInputRedirection>
  <ProtectedClient>Enable</ProtectedClient>
  <MemoryInMB>{memory_mb}</MemoryInMB>
  <MappedFolders>
{}
{}
{}
{mapped_lines}
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -NoProfile -ExecutionPolicy Bypass -File {}\{} -InputPath {} -OutputPath {}</Command>
  </LogonCommand>
</Configuration>
"#,
        mapped_folder(&tools, GUEST_TOOLS, true)?,
        mapped_folder(&input, GUEST_INPUT, true)?,
        mapped_folder(&output, GUEST_OUTPUT, false)?,
        xml_escape(GUEST_TOOLS),
        xml_escape(entrypoint.guest_script()),
        xml_escape(GUEST_INPUT),
        xml_escape(GUEST_OUTPUT),
    ))
}

fn mapped_folder(host: &Path, guest: &str, read_only: bool) -> Result<String> {
    let host = absolute(host)?;
    let host = host.to_string_lossy();
    ensure!(
        !host.contains(['\n', '\r']),
        "sandbox host path contains an unsupported character"
    );
    Ok(format!(
        "    <MappedFolder>\n      <HostFolder>{}</HostFolder>\n      <SandboxFolder>{}</SandboxFolder>\n      <ReadOnly>{}</ReadOnly>\n    </MappedFolder>",
        xml_escape(&host),
        xml_escape(guest),
        if read_only { "true" } else { "false" }
    ))
}

fn absolute(path: &Path) -> Result<PathBuf> {
    ensure!(
        path.is_absolute(),
        "sandbox path must be absolute: {path:?}"
    );
    Ok(path.to_path_buf())
}

fn relative_path(path: &str) -> Option<&str> {
    (path.len() <= 512
        && !path.contains(['\\', ':', '\0', '\n', '\r'])
        && path
            .split('/')
            .all(|part| !part.is_empty() && part != "." && part != ".."))
    .then_some(path)
}

fn is_identifier(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
}

fn is_sha256(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

fn xml_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            other => escaped.push(other),
        }
    }
    escaped
}

#[cfg(windows)]
fn is_reparse_point(path: &Path) -> bool {
    use std::os::windows::fs::MetadataExt;
    fs::symlink_metadata(path)
        .map(|metadata| metadata.file_attributes() & 0x400 != 0)
        .unwrap_or(false)
}

#[cfg(not(windows))]
fn is_reparse_point(_path: &Path) -> bool {
    false
}
